CREATE TABLE IF NOT EXISTS whitelist (
  name TEXT PRIMARY KEY,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blacklist (
  name TEXT PRIMARY KEY,
  reason TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);