#name = "ens-gateway"
name = "beagle"
main = "src/index.ts"
compatibility_date = "2023-03-15"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "offchaindemo"
database_id = "203838a1-1a3a-4cbb-8319-da57e77b7f76"

# The necessary secrets are:
# - PRIVATE_KEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
